### ISSUE TITLE
🐛💻 – Mermaid not rendering graph

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#107]
**Describe the problem**

Mermaid not rendering

**Steps to reproduce**

Visit: https://tides-transit.github.io/TIDES/main/architecture/

**Comment by botanize** [comment]
@e-lo I'm pretty sure this is because the [CDN link](https://github.com/TIDES-transit/TIDES/blob/85ef8fafa0df811a7e7d84702c20a5cd0aebb4e3/mkdocs.yml#L46) is broken. 

We could remove the `extra_javascript` line and let the plugin insert the correct CDN link, or update the CDN to one of:

- https://unpkg.com/mermaid/dist/mermaid.core.mjs or
- https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs

I don't know if ESM is supported by mkdocs or the plugin.

Any preferences?

**Comment by botanize** [comment]
Ah, it's not a broken CDN link, it's an incompatible version (because version 10 is only available as ESM, which isn't supported by mkdocs).

https://github.com/fralau/mkdocs-mermaid2-plugin/issues/70

We can either pin to version 9, or use the work-around suggested in the issue while we wait for compatibility with version 10.
