### ISSUE TITLE
📄🚀 – Combine `fare_media_id` and `fare_media_purchased`

### ISSUE THREAD

**Issue by jaygordon** [TIDES-transit/TIDES#109]
**Describe the feature you want and how it meets your needs or solves a problem**

As a software developer who processes multiple AFC vendors' fare transaction records, having two different fare instrument IDs in `fare_transactions` seems unconventional and perhaps unnecessary. 

I understand that `fare_transactions` can represent the validation of a fare or the purchase of a new fare instrument, but I haven't seen both at the same time in the same record. The AFC systems I’ve seen use a single column for the instrument’s ID. For example, the ID of a card that’s being used at a farebox to validate a boarding, or the ID of a card that’s being purchased (via cash, a bank card, or a mobile device) at a vending machine. Is there another use case the spec is designed to handle that requires these two fields in the same record? For example, is there a system where someone can use one stored value card to purchase another card?

**Describe the solution you'd like**

If there isn't a use case requiring two fields simultaneously I suggest removing `fare_media_purchased`. If a `fare_transaction` has a `fare_action` of `sale` for example, that would indicate that the sole ID is that of the fare instrument being purchased.

On a related note, my two cents would be to rename the remaining `fare_media_id` field to `fare_instrument_id`, `token_id` or some other name that indicates that the field is the identifier of a specific card, ticket, mobile device, etc.

**Comment by jlstpaul** [comment]
Agree that fare_media_purchased doesn't seem to be that important. The only value I can see would be, as noted, linking the purchase of one farecard by using another one.    The naming of fare_media_id addressed in issue #115

**Comment by SorenSpicknall** [comment]
> Is there a system where someone can use one stored value card to purchase another card?

I wanted to add a little color to what James Garner from Pace mentioned on today's contributor call about commuter rail integration in/around Chicago, since it might qualify as the edge case that proves the need.

Chicagoland has CTA (city-run rail and bus transit), Pace (a combined suburban bus and paratransit system), and Metra (commuter rail). CTA and Pace have fare integration through Ventra, a Cubic implementation. Riders can use their Ventra card to tap onto CTA and Pace vehicles.

Metra handles fare validation in a different manner, but there has been significant political impetus to smooth over the gaps between systems (awaiting eventual full integration). In recent years, Metra was brought into a partial implementation of Ventra that added a module to Ventra's mobile app - the module doesn't allow riders to use their normal Ventra card _as_ a farecard for Metra rides, but allows riders to _purchase_ virtual Metra tickets (including multi-ride passes) using their Ventra balance.

I don't actually know how Metra (or Cubic) represents this on the backend, but from outside it seems like a case where value stored on one fare instrument (a Ventra card) is used to purchase another (e.g. a monthly Metra pass).

**Comment by jaygordon** [comment]
@SorenSpicknall and James bring up good points about virtual passes or tickets being loaded onto physical cards or tickets. This illustrates how the term "ticket," like the term "pass," can have two meanings: 1) a physical fare instrument made of paper or some other material and 2) an intangible asset indicating that someone is entitled to some number of rides.

I think these examples can be satisfied by using the ID of the physical card, ticket, or mobile device as the fare instrument ID (currently called `fare_media_id` but possibly being renamed in issue #115) and using the ID of the type of virtual ticket as the `fare_product_id`.
