### ISSUE TITLE
📝 Add direction to work from a branch of main repo rather than a fork

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#193]
Per @danishswag's recent contribution – this needs to be made more obvious in CONTRIBUTING.md

**Comment by Danishswag** [comment]
As a follow-up to this, if we're updating `CONTRIBUTING.md` anyway, another issue I ran into is that the tests it recommends running also requires the packages in `docs/requirements.txt` too since the first test script (`tests/test_local_spec`) builds the docs locally.

If we want to keep the test suite as is, we could maybe just merge the two requirements files?

**Comment by Danishswag** [comment]
Must have been an issue with my Python install, please feel free to ignore
