### ISSUE TITLE
🐛  CI not deleting refs in mike when refs to branches deleted

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#210]
Expected:

[`clean-docs.yml`](https://github.com/TIDES-transit/TIDES/blob/main/.github/workflows/clean-docs.yml) workflow should be deleting the documentation version using [mike's delete functionality](https://github.com/jimporter/mike?tab=readme-ov-file#deleting-docs)

Instead:

...When I deleted branches via the GitHub web UI, the workflow didn't run.

**Comment by e-lo** [comment]
cc: @SorenSpicknall @themightychris

**Comment by SorenSpicknall** [comment]
It looks like the issue here is that our existing set of Action steps in the docs cleaning workflow are triggered based on a filter on PR info, which doesn't exist when there isn't a PR to get info from:

`if: github.event.pull_request.head.repo.full_name == github.repository`

The purpose of that check is to ensure that the Actions in the workflow get skipped on PRs that come in from forks, since those Actions won't be able to function on fork-based PRs without errors. However, this means that when a deletion is made outside of the context or a PR, the if-condition can't be evaluated and the workflow steps under `clean:` are skipped. There are several ways you could resolve this. For instance, you could replace that if-condition with one that checks whether the current run context is in a repo owned by the `TIDES-transit` organization:

`if: github.repository_owner == 'TIDES-transit'`

There are philosophical downsides to making that specific change, chiefly that somebody who forks the repo would have to change the if-condition for the same workflow to work on their work. But since we're already primarily encouraging registered contributors and branch-based (rather than fork-based) PRs, it may be a perfectly workable solution.

**Comment by e-lo** [comment]
Thanks, @SorenSpicknall  - I agree that we can deal with the downsides of the if owner=tides-transit specificity.
