### ISSUE TITLE
🐛 📄 – Wide vs long format for stop_visits (transaction_revenue_x, transaction_count_x)

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#35]
**Describe the problem**
The draft report and the current spec describe a "wide" format for `transaction_revenue_*` and `transaction_count_*` variables in the `stop_visits` file. However, this format is a bit awkward, as it requires adding new columns for new or unspecified media types. Oddly, the `fare_transactions` file uses a long format, encoding the types of media as an enum in the `media_type` field. It's also easier to aggregate the long format, where each media type is its own row, for example (the pivot in this example is untested):

```sql
-- wide
SELECT media_type,
    SUM(transaction_revenue)
FROM 
    (SELECT stop_id, transaction_revenue_cash, transaction_revenue_smartcard, transaction_revenue_magcard, transaction_revenue_bankcard, transaction_revenue_nfc, transaction_revenue_optical, transaction_revenue_operator, transaction_revenue_other
    FROM stop_visits) p
UNPIVOT (revenue FOR media_type IN 
     (transaction_revenue_cash, transaction_revenue_smartcard, transaction_revenue_magcard, transaction_revenue_bankcard, transaction_revenue_nfc, transaction_revenue_optical, transaction_revenue_operator, transaction_revenue_other)) AS unpvt
GROUP BY media_type

-- long
SELECT media_type, SUM(transaction_revenue) revenue, SUM(transaction_count) count FROM stop_visits WHERE stop_id = '1330' GROUP BY media_type
```

**Possible Solutions**

1. Reformat to "long": Add a `media_type` field, add `media_type` to the primary key, replace the `transaction_revenue_x` fields with `transaction_revenue`, and the `transaction_count_x` fields with `transaction_count`. 
2. Leave as "wide" format.

The long format is a simpler representation, with easier aggregation of the data, but it could be harder to add a value to an enum in the spec than to add a new `transaction_count_x` field. However, even if a new enum value weren't in the spec (causing the data to not validate), it still seems like a database and downstream systems would better handle additional unrecognized enum values than additional unrecognized fields (e.g., aggregating fare revenue across media types would require checking for fields starting with `transaction_revenue_`).

Furthermore, many of these media types may come from different subsystems, so would require merging to get the wide format, whereas simply stacking data in the long format is easier (it's much easier to type `cat stop_visits_smartcard.csv stop_visits_cash.csv > stop_visits.csv` in a terminal than load into another program and merge using the primary key fields).

**Comment by gabriel-korbato** [comment]
It would be best to keep the wide format for the `stop_visits` file, and adding columns if necessary in the future.  We could define a SQL view that sums all the fields of a group for the convenience of querying, so that people don't have to add the fields every time they query.  This would expose a `transaction_revenue_total` field that would be calculated on the fly.  (It would not be a good idea to add that as a field to the spec.)  

It would be possible to convert this to long format without violating normalization rules by adding a `transaction_revenue` file that has one or more rows for each row in the stop visit file.  That file would have a foreign key to the `stop_visits` file and the fields suggested in possible solution #1.  However, users would have to perform an additional join and all the columns of the primary key in the `stop_visits` file would be copied, so I don't think it's worth doing.  

Implementing solution #1 in the same table would violate [normalization rules](https://en.wikipedia.org/wiki/Database_normalization#Satisfying_2NF), introducing various issues.  It would require repeating all other rows of the table, which wouldn't be efficient and isn't best practice.

**Comment by gabriel-korbato** [comment]
The reason the `fare_transaction` file uses the long format for media type is because each row represents a single transaction, performed with a single media type.  There is no need to repeat rows.  This isn't the case with `stop_visits`, since the transaction fields in that file are aggregations/summaries of transactions.

**Comment by gabriel-korbato** [comment]
This issue was assigned to Joey and I in our last Teams meeting, so that we review it and suggest how to proceed.  Here's my take.  Joey brought up this issue, pointing out the difficulty of adding fields in the future, and this is a symptom of using a non-normalized structure (a list of columns that can grow if categories are added later).  

If I were designing this table with the requirement to have the breakdown of transactions by media, I would resolve this issue by implementing Joey's first solution, but on a separate table to avoid repeating all other fields (because that would violate normalization rules in a different way, forcing us to represent a single stop visit in multiple rows).  We would remove all `transaction_revenue_x` and `transaction_count_x` fields from the `stop_visits` table, and we would define a new table `stop_visit_transactions` with `media_type`, `transaction_revenue`, `transaction_count`, and the primary key column or columns to a single row in `stop_visits`.  There would be a one-to-many relationship between `stop_visits` and `stop_visit_transactions`.  (For the sake of efficiency, I would also add a surrogate primary key to the `stop_visits` table, so that we can point back to each stop visit with a single numeric column, but that's another discussion and the solution could be implemented regardless.)

If I were designing this table without the requirement to have the breakdown of transactions by media, I would remove all `transaction_revenue_x` and `transaction_count_x` fields from the `stop_visits` table.  The breakdown is not really needed in this table because one can join the `fare_transactions` table to `stop_visits` and count transactions grouping by stop visit and media type.  We could provide a SQL example for how to do this in the documentation or somewhere else in this repo.  I think this is the best way forward.

**Comment by gabriel-korbato** [comment]
Also note that a similar issue exists with `station_activities`, so whatever solution we decide on should also be applied to that other table.

**Comment by jlstpaul** [comment]
> If I were designing this table without the requirement to have the breakdown of transactions by media, I would remove all transaction_revenue_x and transaction_count_x fields from the stop_visits table. The breakdown is not really needed in this table because one can join the fare_transactions table to stop_visits and count transactions grouping by stop visit and media type. We could provide a SQL example for how to do this in the documentation or somewhere else in this repo. I think this is the best way forward.

I like this suggestion best.  My only concern is to make sure that it is clear how to link from the `stop_visits` or `station_activities` record back to the associated `fare_transactions` records, especially if there is any complex logic as to which `fare_transactions` are actually included in the aggregation.

This would also eliminate issue #114
