### ISSUE TITLE
🐛📄 – Valid IDs may not exist in GTFS

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#50]
**Describe the problem**

If MetroTransit creates a new trip with a new trip_id to fill a service gap, that trip_id won't appear in GTFS trips.txt. None of the additional information provided by GTFS (service_id, route_id, direction_id, scheduled times and distances) would be available for trips with IDs that don't match the static GTFS. This would prevent aggregation of event data, and inclusion in KPIs.

For example, if I insert a new trip into a 40 minute headway gap, the new trip_id won't be in GTFS, the headway KPI won't be able to identify that trip as belonging to the same route-direction as the surrounding trips, so the calculated headways will be 40 instead of 20 minutes.

**Possible Solutions**

- Add supplementary tables for service adjustments, following GTFS-realtime Service Changes: new_routes, new_trips, new_shapes, new_stops. This would make the content of service adjustment available to TIDES for matching and aggregation, but we'd be replicating parts of GTFS-realtime ServiceChanges into TIDES.

**Additional context**

**Comment by gabriel-korbato** [comment]
TIDES allows operated trips to have a null scheduled trip ID.  It is the scheduled trip that points to GTFS, not the operated trip.  Aggregation should happen across operated trips, so it shouldn't matter if the trip appears in GTFS.  The trips_performed table has route_id, shape_id, and direction_id, which could be populated even if the trip wasn't scheduled.  This is why those fields were included in that table.

**Comment by botanize** [comment]
Ah, sure. However, a new `shape_id` (that doesn't exist in GTFS static) means I don't have access to `shape_dist_traveled` or even the shape geometry with which I could calculate scheduled distances. A new `route_id` means I may not have a `route_short_name`/`route_long_name` pair available, nice when your `route_id` is 901 but your route name is "METRO Blue Line". New `trip_id`s mean no `trip_headsign`, `block_id`, &c.

Maybe the answer is just, if you need extended properties, you need to supply them yourself. This could be the basis for a detailed best practice.

**Comment by e-lo** [comment]
Also to consider is GTFS RT TripDesriptor and their uniqueness requirements should a `trip_id` not be present in published GTFS Schedule...

For a frequency-based schedule where there is one `trip_id` but many trips, they should be uniquely defined w/
- `trip_id`
- `start_time` (which should be stable...even if it isn't true!?)
- `start_date`

Alternatively:

- `route_id`
- `direction_id`
- `start_time` (although this is supposed to reference GTFS Static)
- `start_date`

And then in the GTFS Realtime [`TripProperties`](https://gtfs.org/realtime/reference/#message-tripproperties) message, you can define additional identifiers for DUPLICATED trips as:
- `trip_id` (for new trip, the orig trip would be in the [`TripDescriptor`](https://gtfs.org/realtime/reference/#message-tripdescriptor) and allow you to reference `route_id`, etc. 
- `start_time` 
- `start_date`

We could (not mutually exclusive options)
(1) Add the alternative identifier fields (route/direction/start date/start time) into TIDES in the event that `trip_id` is not available.
(2) Add TripProperties as a supplemental/related table.
...

**Comment by mpaine-act** [comment]
Since we are talking about trip_id in the _past tense_ for manually ran trips, another option is for MetroTransit to update their GTFS trips.txt with the new trip_id.   If that trip_id is unique for a single day, calendar.txt would also need to be touched with a new service_id unique to that trip_id on that date and/or time.

I do prefer the idea of having a supplementary table for recording GTFS-RT ServiceChanges (new_routes, new_trips, new_shapes, new_stops), although that draft was closed and isn't official.

One last idea is to have a Trips table which purpose is to generate a unique trip_id PK to be used in all other tables, so composite keys are needed in other tables (ie. Trips Performed).   Then any number of secondary key columns can exist in the Trips table to find uniqueness under the different scenarios [e-lo](https://github.com/e-lo) mentioned.

**Comment by jlstpaul** [comment]
This is listed as a V1.0 milestone, but it is not clear what the recommended resolution is.  I like the idea of creating links to GTFS Service Changes data when that is solidified. And I also see the option to modify the GTFS schedule files to reflect service as delivered as opposed to service as scheduled if that is of value to an agency. 

For now, I don't see changes suggested to the spec itself that are on the critical path to V1.0

**Comment by botanize** [comment]
I think this is still a v1.0 milestone because we need to resolve in the spec what, if any, relationship is expected between TIDES and GTFS. If the answer is, use your GTFS ids when you can, but otherwise don't expect any relationship, that's fine, but it should be documented.

**Comment by tsherlockcraig** [comment]
Connecting to GTFS Service Changes (or, easily facilitating a connection to GTFS Service Changes), seems like a great way to have TIDES reinforce some order in the GTFS ecosystem. If we need to wait for finalization of pieces of that spec in order to reference it cleanly, some type of 'punt' does seem warranted on this issue. But that doesn't preclude offering clear documentation in the short term as suggested by @botanize
