### ISSUE TITLE
📄🚀 – add optional `count` field to passenger_events table

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#73]
**Describe the feature you want and how it meets your needs or solves a problem**

As a developer of data transformation tools, I want a more flexible and potentially more compact representation of event data.

If I understand the passenger_events table correctly, each passenger boarding would be a separate row. Our system does not report individual passenger boarding events, only a single aggregate event. Here's a sample of the rawest APC messages we have access to (some fields removed): 

|     date| vehicle_id|message_timestamp   | passenger_count_on| passenger_count_off|
|--------:|----------:|:-------------------|------------------:|-------------------:|
| 20220930|       4062|2022-09-30 09:22:22 |                  3|                   0|
| 20220930|       3749|2022-09-30 09:22:48 |                  1|                   0|
| 20220930|       2490|2022-09-30 09:22:48 |                  0|                   1|
| 20220930|       3794|2022-09-30 09:37:59 |                  1|                   0|
| 20220930|       2678|2022-09-30 10:41:29 |                  1|                   0|

In the existing spec the first row of the above table would be represented as:

|passenger_event_id|date|timestamp|trip_id_performed|stop_sequence|event_type|vehicle_id|
|-|-|-|-|-|-|-|
|20220930_t1_s1_1|2022-09-30|2022-09-30 09:22:22|t1|1|Passenger boarded|4062|
|20220930_t1_s1_2|2022-09-30|2022-09-30 09:22:22|t1|1|Passenger boarded|4062|
|20220930_t1_s1_3|2022-09-30|2022-09-30 09:22:22|t1|1|Passenger boarded|4062|

**Describe the solution you'd like**

The implied count for each row in passenger_events is 1. Let's make that explicit and modifiable with an optional `count` field (positive integer) with a default value of 1. It would be much easier and more compact to represent our passenger events, and be completely backward compatible, e.g.:

|passenger_event_id|date|timestamp|trip_id_performed|stop_sequence|event_type|vehicle_id|count|
|-|-|-|-|-|-|-|-|
|20220930_t1_s1|2022-09-30|2022-09-30 09:22:22|t1|1|Passenger boarded|4062|3|
|20220930_t1_s1|2022-09-30|2022-09-30 09:22:22|t1|1|Ramp was deployed|4062||

Here there's an explicit count provided for the passenger boardings, but none provided for ramp deployed, meaning it happened once.

Alternatively, `count` could be optional but not nullable, so if you provide any value in the `count` field you must provide a value for all rows. That may be a detail left to implementers, simply specifying that the default is 1 if empty should be enough.

This would be useful for not just passenger boardings and alightings, but door opens and other fields, which might happen more than once at a stop, but have a single record in the CAD/AVL system.

Aggregation would change from counting to summing:

```sql
# existing spec: count
SELECT date, trip_id_performed, COUNT(*) AS trip_boardings FROM passenger_events WHERE event_type = 'Passenger boarded' GROUP BY date, trip_id_performed

# proposed spec: using coalesce if the loader doesn't replaces empty counts with 1
SELECT date, trip_id_performed, SUM(COALESCE(count, 1)) AS trip_boardings FROM passenger_events WHERE event_type = 'Passenger boarded' GROUP BY date, trip_id_performed

# proposed spec: using DEFAULT  1 for the count column
SELECT date, trip_id_performed, SUM(count) AS trip_boardings FROM passenger_events WHERE event_type = 'Passenger boarded' GROUP BY date, trip_id_performed
```

**Describe alternatives you've considered**

Continue to expand aggregated data so that the only difference among a set of rows is the primary key, `passenger_event_id`.

**Additional context and sample data**

**Comment by gabriel-korbato** [comment]
The `passenger_events` table is meant to record individual events happening at a specific instance in time, as generated by AVL/APC systems.  Although some APC vendors expose event-level data, including passenger boardings and alightings but also wheelchair ramp deployments, others process this data to generate stop-level passenger count summaries.  If your system only generates stop-level data, then you should skip this file and represent that in the `stop_visits` table, using `boarding_1`, `boarding_2`, `alighting_1`, `alighting_2`, and `load`.  The `passenger_events` data could be used for detailed dwell time modeling and to generate stop-level data if and when that data are available, but I suspect that many users will skip it.  

This would leave you with two `stop_visits` files, one coming from your AVL system and one from your APC system, since it appears that your agency has separate hardware for both of these.  Not a problem—in fact this is in line with TIDES discussions from early on—but I imagine you would be interested in a tool to merge those two data sources and generate a third `stop_visits` file, whether developed by you or others.

**Comment by botanize** [comment]
I could trivially back-transform `stop_visits` style data into `passenger_events` with this one minor change, which could open up options to use tools that require the `passenger_events` table.

For example, `stop_visits` doesn't let me distinguish between second- and third-door boardings and alightings, which is important for some of the work I do on modeling boarding and alighting time. But I can use `passenger_events.device_id` to easily distinguish doors—*if* there's a count field. Without the count field I *must* use `passenger_events` to distinguish the second and third doors, but I also have to replicate each `Passenger boarded` `event_type` for each boarding, it's pointlessly wasteful.

On the other hand, when a count is more than 1, there are somethings you have to assume. For example, if I'm trying to understand the distribution of boarding time per passenger, I can look at the time between count 1 events, or I have to use the average implied by (door_close - door_open) / count. However, that's simple logic to build into such a tool.

**Comment by gabriel-korbato** [comment]
Another argument in favor of adding this field is that it is possible for some APC hardware to provide aggregated counts between logged events, for example, the number of passengers boarded since the last event 5 seconds ago.  I don't have a specific example in mind, but adding the field could accommodate that need if and when it arises. 

I still think that if the data provided by a vendor is at the stop level, the `stop_visits` file is the right format to put that in, but if you have timestamped lower-level logs including of things between stops, or if it is provided separately for each counting device, `passenger_events` is the file for that.  

> For example, `stop_visits` doesn't let me distinguish between second- and third-door boardings and alightings, which is important for some of the work I do on modeling boarding and alighting time. 

This is a good argument for adding at least one more optional door field to `stop_visits`.

**Comment by botanize** [comment]
Back to the old wide vs long debate. We've got vehicles with 6 doors, do we use 6 boarding and 6 alighting fields? I think this is a great reason to make passenger_events more flexible, because we can represent these things with device_id and it scales simply to any number of doors or devices. Someone could even have two sets of independent APC devices, and want to track those separately, easily done in the "long" format with passenger_events.device_id, but kinda nuts in the wide format of stop_events.

**Comment by gabriel-korbato** [comment]
Jay and I have been reviewing the spec and will be creating several issues over the next week or two.  One of them is the idea that passenger_events should be generalized to device_events.  More to come...

**Comment by mpaine-act** [comment]
What about other types of events that are not integer based but floats or strings?   Should this new "value" field be defined as a string to handle all cases?

**Comment by botanize** [comment]
@mpaine-act I think the functionality you want would be implemented by adding another option to the `event_type` field. Can you give an example that illustrates your use-case?

**Comment by mpaine-act** [comment]
Some ideas for additional passenger event_type.enums include some value with them:

['Farebox amount added (decimal)", "Found lost item (string)", "Item missing (string)", "Safety event (string)", "Stop requested", "Pickup requested (stop_id)"].   For the latter, the stop_id could be different than the current stop_id.

Since TIDES is setup for fixed route service, I don't know if flex route service events would work with stop_id (perhaps lat/long is good enough).

I might be thinking more about incident_events rather than passenger_events, which a completely different discussion -- I have 250+ incident type events in our operations data, i.e. Accident - BUSvBUS, Trip Cancel - No Work Force, Road Call (reason), etc.

[IncidentTypes.txt](https://github.com/TIDES-transit/TIDES/files/10222939/IncidentTypes.txt)
