### ISSUE TITLE
🐛📄 – odometer is type integer, should be number

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#86]
**Describe the problem**

`vehicle_locations.odometer` is type `integer`, says it references GTFS-realtime, but that is of type `double`, and it seems like sub-meter resolution should be supported.

**Possible Solutions**

Change from `integer` to `number`.

**Additional context**

**Comment by jaygordon** [comment]
I agree that sub-meter resolution should be supported, but an integer (for example integer centimeters) has the advantage of avoiding overrepresenting precision and of filtering out rounding errors.  To get the best of both approaches, should we consider using a real number but limiting its scale? This would have the benefit of keeping the units in meters while avoiding bloating json or csv files with superfluous decimal places (for example, when converting feet to meters or due to rounding errors in some programs or databases).

This could be part of the field definition if possible. For example, in SQL parlance, a data type of DECIMAL(11, 2) would allow centimeter resolution (e.g., 12,345.67 meters) but would force the TIDES adopter to round (or less preferably, truncate) the value. Another option is to make the scale and rounding a best practice.

**Comment by botanize** [comment]
Thanks Jay. In theory, the frictionless `format` attribute for `number` fields would allow us to specify a precision, e.g., `%.2f`, but it looks like [number formats](https://specs.frictionlessdata.io/table-schema/#number) are not actually supported by frictionless. I think this would be a good fit for a best practice, and the guidance could be incorporated into the odometer field description.
