### ISSUE TITLE
🚀💻  Define profile for `datapackage.json`

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#93]
**Describe the feature you want and how it meets your needs or solves a problem**

As a , I want  so that .

*As a user, I'd like to know if my `datapackage.json` is valid for TIDES...not the more general `datapackage.json`.*

**Describe the solution you'd like**

- [x] Define a `tides-datapackage` [profile](https://specs.frictionlessdata.io/profiles/) in `/spec` which has more requirements and defined fields than the [`tabular-datapackage` profile.](https://specs.frictionlessdata.io/tabular-data-package/#language) 
- [x] Validate that `tides-datapackage.json` profile is consistent with the [profile definition](https://specs.frictionlessdata.io/profiles/)
- [x] Validate that all `datapackage.json `files in sample dir reference and are consistent with `tides-datapackage` profile.

**Describe alternatives you've considered**

**Additional context**

**Comment by SorenSpicknall** [comment]
Tagging in @e-lo, @j-meelah, and @botanize because all three of y'all contributed to review/acceptance for the initial schema definitions, which included [the initial spec JSON](https://github.com/TIDES-transit/TIDES/blob/main/spec/tides.spec.json) that references the desired `tides-data-package` profile.

What specific additional properties or behaviors did you have in mind for the `tides-data-package` profile that aren't present on the underlying `tabular-data-package` profile? On first glance, it looks like the `required` property under `resources` is an addition to [the underlying tabular data resource](https://specs.frictionlessdata.io/schemas/tabular-data-resource.json), but I also see [some old conversation indicating that its presence may not be necessary](https://github.com/TIDES-transit/TIDES/pull/1#discussion_r947076906). Is there a canonical place where the extended requirements we wish to impose on (or extend from) the underlying profile are outlined?

**Comment by e-lo** [comment]
@SorenSpicknall can you submit PRs addressing the final two check-boxes? This is related to some of the other CI work that I think you are working on.
